// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvBK5_gM8E-Q5Eect58jzqIotpcQt2FTc',
    appId: '1:61185331927:web:b2bcc9e71efedce0cd9692',
    messagingSenderId: '61185331927',
    projectId: 'planetcare-72029',
    authDomain: 'planetcare-72029.firebaseapp.com',
    databaseURL: 'https://planetcare-72029-default-rtdb.firebaseio.com',
    storageBucket: 'planetcare-72029.firebasestorage.app',
    measurementId: 'G-NM98L346Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW59OEHa_sV85zixOO2MF2laoc-LCP1g0',
    appId: '1:61185331927:android:7d6308926f3656f8cd9692',
    messagingSenderId: '61185331927',
    projectId: 'planetcare-72029',
    databaseURL: 'https://planetcare-72029-default-rtdb.firebaseio.com',
    storageBucket: 'planetcare-72029.firebasestorage.app',
  );
}
